# Generated by Django 3.2.8 on 2022-01-14 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='para',
            fields=[
                ('paraid', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='survey',
            fields=[
                ('tranid', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('desc', models.CharField(max_length=500)),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('paraid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.para')),
            ],
        ),
    ]
