# Generated by Django 3.2.8 on 2022-01-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220118_1148'),
    ]

    operations = [
    ]
